### PR TITLE
Changed loading dataframe order of operations

### PR DESCRIPTION
**Pull request by tanevitt**
Change order of operations when loading data frames so that we truncate the DataFrame based on what has already been loaded to database before we condense rows down into `other_detail` JSON object, which is a computationally expensive process.

### CODE REVIEW

**Comment by SyXuan** [comment]
Do the changes made in `load_test_data` also need to be made in `load_cycle_stats`?

**Comment by tanevitt** [comment]
> 

Good thought! I'm thinking the answer is no for two reasons:

1. Our cycle_stats inserts will always be small (<10,000 rows), so there is not much computational cost. 
2. Because we often might update the methods we use to calculate cycle statistics (e.g. changing user transformation methods) BattETL currently overwrites (deletes and reinserts new cycle stats) for the intersection (determined by cycle) of existing database cycle stats and any new cycle stats we are trying to insert.

**Review by chintanp — APPROVED** [review]
LGTM! Good work with this, any stats on the improvement in time this brings?

**Review by SyXuan — APPROVED** [review]
LGTM!!

**Comment by tanevitt** [comment]
> LGTM! Good work with this, any stats on the improvement in time this brings?

No, but it's save quite a bit of time as creating the "other" field requires iterating through every row in the data Dataframe, which can take quite a while.

**Pull request merged**
